name: notes_app
description: A simple Flutter notes app with Hive local storage, category management, search, favorites, and animations.
version: 1.0.0+1
author: Godwin Igbokwe
homepage: https://github.com/Flexydea/notes_app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  uuid: ^4.4.0
  lottie: ^3.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/animations/delete.json
    - assets/animations/empty.json

  uses-material-design: true
